<?php

namespace AppBundle\Repository;

/**
 * ArcticlesUERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArcticlesUERepository extends \Doctrine\ORM\EntityRepository
{
}
