<?php

namespace AppBundle\Repository;

/**
 * ArticlesEURepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesEURepository extends \Doctrine\ORM\EntityRepository
{
}
