<?php

namespace AppBundle\Repository;

/**
 * DiapoCarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiapoCarteRepository extends \Doctrine\ORM\EntityRepository
{
}
