<?php

namespace AppBundle\Repository;

/**
 * Diapo_AccueilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Diapo_AccueilRepository extends \Doctrine\ORM\EntityRepository
{
}
