app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_manual:
    path: '/login/'
    defaults: { _controller: FOSUserBundle:Security:login }
